name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1️⃣ - Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2️⃣ - Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3️⃣ - Run unit tests
      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "test_*.py"

      # Step 4️⃣ - Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5️⃣ - Build and Tag Docker Image
      - name: Build and Tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          COMMIT_SHA=${{ github.sha }}
          
          # Build image
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:sha-${COMMIT_SHA::7} .

      # Step 6️⃣ - Push Docker Images
      - name: Push Docker images
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          COMMIT_SHA=${{ github.sha }}

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:sha-${COMMIT_SHA::7}
